nodeLinker: node-modules

catalog:
  zod: ^4
  better-result: ^2.6.0
  drizzle-orm: ^0.44.5
  "@libsql/client": ^0.17.0
  drizzle-kit: ^0.31.4

catalogs:
  pi:
    "@mariozechner/pi-coding-agent": ^0.54.2
    "@mariozechner/pi-tui": ^0.54.2
