import type { MemoryPaths } from "./paths";

export function renderReadPathPrompt(paths: MemoryPaths, summary: string): string {
  return [
    "# Pi OHM Memory",
    "",
    `Memory root: ${paths.data}`,
    "",
    "A memory summary has already been injected below. Do not open memory_summary.md again unless the user explicitly asks to inspect that file.",
    "",
    "Memory layout:",
    "- memory_summary.md: injected summary only",
    "- MEMORY.md: searchable registry and routing layer",
    "- raw_memories.md: raw extracted memories",
    "- rollout_summaries/: per-session summaries",
    "- extensions/ad_hoc/notes/: explicit user-requested update notes",
    "",
    "Quick memory pass:",
    "1. Use the injected summary first.",
    "2. If details matter, search MEMORY.md and then the referenced rollout_summaries files.",
    "3. Verify stale memory against current repo files before acting on it.",
    "4. Skip memory when it is irrelevant or would conflict with current user instructions.",
    "",
    "Citation contract:",
    "If you use memory files, append exactly one hidden citation block as the last content of the final answer:",
    "<oai-mem-citation>",
    "<citation_entries>",
    "MEMORY.md:1-3|note=[why this memory mattered]",
    "</citation_entries>",
    "<rollout_ids>",
    "rollout UUIDs when known",
    "</rollout_ids>",
    "</oai-mem-citation>",
    "",
    "Only write ad-hoc memory update notes when the user explicitly asks you to remember something.",
    "",
    "========= MEMORY_SUMMARY BEGINS =========",
    summary,
    "========= MEMORY_SUMMARY ENDS =========",
  ].join("\n");
}
